from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse

from auth import TokenData, get_current_user
from export_tools import EXPORT_DIR


router = APIRouter(prefix="/exports", tags=["exports"])


@router.get("/{filename}")
async def download_export(
    filename: str,
    _current_user: TokenData = Depends(get_current_user),
):
    """Download an artifact generated by the export_artifact builtin tool."""

    candidate = (EXPORT_DIR / Path(filename).name).resolve()
    export_root = EXPORT_DIR.resolve()
    if export_root not in candidate.parents or not candidate.is_file():
        raise HTTPException(status_code=404, detail="Export not found")

    return FileResponse(candidate, filename=candidate.name)
